joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 3.73064127613788
    has_acceleration_limits: true
    max_acceleration: 18.7468869282902
  joint_2:
    has_velocity_limits: true
    max_velocity: 2.48709418409192
    has_acceleration_limits: true
    max_acceleration: 16.0024613992842
  joint_3:
    has_velocity_limits: true
    max_velocity: 2.71540943019156
    has_acceleration_limits: true
    max_acceleration: 19.6734124150039
  joint_4:
    has_velocity_limits: true
    max_velocity: 3.73064127613788
    has_acceleration_limits: true
    max_acceleration: 19.9181424827185
  joint_5:
    has_velocity_limits: true
    max_velocity: 2.87060410727889
    has_acceleration_limits: true
    max_acceleration: 22.5367210460095
  joint_6:
    has_velocity_limits: true
    max_velocity: 5.96902604182061
    has_acceleration_limits: true
    max_acceleration: 31.8348055563766
